import time

#I autori di clash royale python 1.0
print("Clash Royale Python 1.0")
print("")
time.sleep(1)
print("Programmers:")
time.sleep(1)
print("ZhenTing Lei")
time.sleep(1/5)
print("game account tag l9v9qcqc")
time.sleep(1/5)
print("")
time.sleep(1/5)
print("Giovanni DeSabbata")
time.sleep(1/5)
print("game account tag gj9ljcq8g")
time.sleep(1/5)
print("")
time.sleep(1/5)
print("Chand Sipione")
time.sleep(1/5)
print("game account tag uyql8gpuv")
time.sleep(1/5)
print("")
time.sleep(1)
print("join our clan! It's called clsastrunz")
time.sleep(1)
print("")
time.sleep(1)
print("Idea from:")
time.sleep(1)
print("Giovanni DeSabbata")
time.sleep(1/5)
print("Aman Hossain")
time.sleep(1/5)
print("Chand Sipione")
time.sleep(1/5)
print("Samuele Driussi")
time.sleep(1/5)
print("ZhenTing Lei")
time.sleep(1)
print("")
time.sleep(1)
print("help and supports:")
time.sleep(1)
print("Copilot")
time.sleep(1)
print("")
time.sleep(1)
print("Clash Royale game rights:")
time.sleep(1/5)
print("Sup\nerc\nell")
time.sleep(1/5)
print("")
print("more info on:")
time.sleep(1/5)
print("https://supercell.com/en/")
time.sleep(1/5)
print("")
time.sleep(1)
print("thanks for playing❤️ !")